### PR TITLE
Helm Chart and CD Workflow

### PR DESCRIPTION
**Pull request by rblaine95**
* Initial Helm and Continuous Deploy Workflow
* Update Prettier `--ignore-path`
  * Prettier uses `.gitignore` and `.prettierignore` by default
  * By specifying `--ignore-path .gitignore`, `.prettierignore` appears to
  be ignored, unlike `eslint --ignore-path` which is in addition to
  `.eslintignore`
  * Add `helm` to `.eslintignore` too

Relates to #1

### CODE REVIEW

**Comment by rblaine95** [comment]
@wdbasson @jakubkoci, take a look, let me know what you think, feel free to turn the pedantic dial up to 11.

**Comment by rblaine95** [comment]
@jakubkoci, I noticed the Swagger UI (`/api/docs/ui`) isn't available when using the deployed endpoint (https://ssi-trust-registry.cloudapi.dev.didxtech.com/api/docs/ui) but it is up if I `yarn dev` and go to `http://localhost:3000/api/docs/ui`.

It also doesn't work if I `kubectl port-forward 3000` to the pod/service and go to `http://localhost:3000...`
Is this by design?

**Review by jakubkoci — APPROVED** [review]
Mostly an educational review for me :) It's definitely not my domain. But it seems like a lot of stuff to run one service 🤔

**Comment by jakubkoci** [comment]
@rblaine95 Yes, I decided to hide API docs at the start. But we can eventually easily allow.

> It also doesn't work if I kubectl port-forward 3000 to the pod/service and go to http://localhost:3000...

I'm not sure if I understand what's the problem there 🤔

**Comment by rblaine95** [comment]
>I'm not sure if I understand what's the problem there 🤔

It's no problem, I was just trying to understand why I couldn't access the Swagger UI (was afraid maybe I broke something).

If you `kubectl port-forward` you can access a pod/service in K8s via `http://localhost:xyz`, which makes the pod _think_ it's being accessed from itself.
Usually it's useful for cutting out middlemen (like loadbalancers/ingress controllers/etc to test if anything in the chain is causing issues) and to access endpoints that can only be accessed from the `localhost` interface, like if you have a `/api/admin` that you only want `localhost` to be able to access.

I suspected that the Swagger UI was only accessible from `localhost`, hence the test, but it also didn't work.

**Review by wdbasson — APPROVED** [review]

**Pull request merged**
